version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    container_name: django

    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SECRET_KEY=foo
volumes:
  postgres_data: